Include severity-threshold param

diff --git a/.github/workflows/snyk-scan.yml b/.github/workflows/snyk-scan.yml
--- a/.github/workflows/snyk-scan.yml
+++ b/.github/workflows/snyk-scan.yml
@@ -43,7 +43,7 @@ jobs:
       # exit code 1: Vulnerabilities found
       # exit code 2: An error occurerd
       - name: Run Snyk on project
-        run: snyk test --file=app/build.gradle.kts --sarif --continue-on-error --debug > snyk_report.sarif || true # manual override to prevent failure
+        run: snyk test --file=app/build.gradle.kts --sarif --severity-threshold=high --continue-on-error --debug > snyk_report.sarif || true # manual override to prevent failure
         env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
 
